services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - COSMOS_ENDPOINT=https://host.docker.internal:8081/
#    extra_hosts:
#      - "host.docker.internal:host-gateway"